#include "FWCore/Framework/interface/one/EDAnalyzer.h"
#include "FWCore/Framework/interface/Run.h"
#include "FWCore/Framework/interface/Event.h"
#include "FWCore/Framework/interface/EventSetup.h"
#include "FWCore/Framework/interface/MakerMacros.h"
#include "FWCore/ParameterSet/interface/ParameterSet.h"
#include "FWCore/ServiceRegistry/interface/Service.h"
#include "FWCore/Utilities/interface/EDGetToken.h"
#include "FWCore/Utilities/interface/InputTag.h"
#include "CommonTools/UtilAlgos/interface/TFileService.h"
#include "DataFormats/Common/interface/Handle.h"

#include "L1Trigger/L1TTrackMatch/interface/Setup.h"

#include <TProfile.h>
#include <TH1F.h>
#include <string>
#include <vector>

namespace l1GTT {

  /*! \class  l1GTT::AnalyzerTF
   *  \brief  Class to analyze hardware like structured TTTrack Collection generated by Track Formatter
   *  \author Thomas Schuh
   *  \date   2025, June
   */
  class AnalyzerTF : public edm::one::EDAnalyzer<edm::one::WatchRuns, edm::one::SharedResources> {
  public:
    AnalyzerTF(const edm::ParameterSet& iConfig);
    void beginJob() override {}
    void beginRun(const edm::Run& iEvent, const edm::EventSetup& iSetup) override;
    void analyze(const edm::Event& iEvent, const edm::EventSetup& iSetup) override;
    void endRun(const edm::Run& iEvent, const edm::EventSetup& iSetup) override {}
    void endJob() override {}

  private:
    // ED input token of tracks
    edm::EDGetTokenT<tt::StreamsTT> edGetToken_;
    // Setup token
    edm::ESGetToken<Setup, tt::SetupRcd> esGetToken_;
    // occupancy profile
    TProfile* prof_;
    // occupancy histogram
    TH1F* his_;
  };

  AnalyzerTF::AnalyzerTF(const edm::ParameterSet& iConfig) {
    usesResource("TFileService");
    // book in- and output ED products
    const std::string& label = iConfig.getParameter<std::string>("OutputLabelTF");
    const std::string& branch = iConfig.getParameter<std::string>("Branch");
    edGetToken_ = consumes<tt::StreamsTT>(edm::InputTag(label, branch));
    // book ES product
    esGetToken_ = esConsumes<edm::Transition::BeginRun>();
  }

  void AnalyzerTF::beginRun(const edm::Run& iEvent, const edm::EventSetup& iSetup) {
    // helper class to store configurations
    const Setup* setup = &iSetup.getData(esGetToken_);
    // book histograms
    edm::Service<TFileService> fs;
    TFileDirectory dir;
    dir = fs->mkdir("TF");
    // channel occupancy
    constexpr int maxOcc = 180;
    const int numChannels = setup->tfNumChannel();
    his_ = dir.make<TH1F>("His Channel Occupancy", ";", maxOcc, -.5, maxOcc - .5);
    prof_ = dir.make<TProfile>("Prof Channel Occupancy", ";", numChannels, -.5, numChannels - .5);
  }

  void AnalyzerTF::analyze(const edm::Event& iEvent, const edm::EventSetup& iSetup) {
    int chan(0);
    for (const tt::StreamTT& streamTT : iEvent.get(edGetToken_)) {
      his_->Fill(streamTT.size());
      prof_->Fill(chan++, streamTT.size());
    }
  }

}  // namespace l1GTT

DEFINE_FWK_MODULE(l1GTT::AnalyzerTF);
